services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: bash -c "goose -dir migrations postgres \"host=${DB_HOST} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB}\" up && go run service-app"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      retries: 5
